### ISSUE TITLE
save error

### ISSUE THREAD

**Issue by 345thomas** [pypyr/pypyr-cli#139]
save error information from both the _swallow_ and the _retry_ decorators to context, so that subsequent steps can use them. 

also make err available in the on_failure handler.

**Comment by Reskov** [comment]
I have internally tested something close to

```yaml
- name: steps.update_status
  failure: # will be formatted and added to context at key "failure->info" only when failure occurs
    code: 'UPDATE_FAILED'
    reason: Update status was failed due to a reason '{update_reason}'.
```

And actual code part

```python
async def run_pipeline_steps(steps, context):
    ...
    for step in steps:
        try:
            await Step(step).run_step(context)
        except Exception as e:
            # Exceptions could also happened on the step init phase (ModuleNotFound, KeyError, etc..), 
            # put exception handler here because of that. But unfortunately 
            # current limitation is that this code does not care about swallowed exceptions.
            set_context_failure(context, step, exception=e)
            raise
    ...


def set_context_failure(context, step, exception):
    failure = {
        'exception_name': get_error_name(exception),
        'exception': exception,
        'info': {}
    }
    if isinstance(step, dict):
        failure['step_name'] = step['name']
        if 'failure' in step:
            failure['info'] = context.get_formatted_iterable(
                step['failure']
            )

        if hasattr(step, 'lc'): # need to set roundtrip parser by default, but will not fail if not set.
            failure['lc'] = {'line': step.lc.line, 'col': step.lc.col}
    else:
        failure['step_name'] = step

    if context.get('failure'):
        # keep original exception info on top
        position = context['failure']
        while position.get('next'):
            position = position['next']
        position['next'] = failure
        raise
    else:
        context['failure'] = failure
```

Do you agree in general, can I prepare a PR for that? 
Opened questions are: 
- how to catch swallowed exceptions?
- it is not very convenient to format variables on failure info, because is needed to set all of them before  code part with potential explosion
- can we safely set default yaml parser to roundtrip?

**Comment by 345thomas** [comment]
thanks so much for this Reskov, and thank you for your patience, I wanted to think it through carefully. . .

my plan here was to do this in in the `dsl.Step` class, in `run_conditional_decorators`. This way the Step has ownership of how it handles errors.

On the `Step.__init__` to set props for `line_no` and `line_col` that the step can use later.

doing it here answers your Q1: on ln 336 is exactly where the swallow check happens, so the idea was only to save the err details if `swallow_me == True`

it also answers Q2, because now it's happening after the 💥 

re yaml_parser: no idea! I suspect it's safe. . . I'm very very very grateful 🙇  that you've taken the trouble to go and hunt down how to get the line numbers/cols in the source yaml for the error, it was on my to do list but it wasn't documented so clearly (or at least I remember not finding the info so easily, maybe my google-fu just failed me) so I am quite happy I don't have to go and find that!

The context for the err list should prob look like this:
```
runErrors:
    - name: get_error_name(exception)
      description:  str(exception)
      line: 2
      col: 4
      customError: #optional
           code: 'from step>onError.code'
           description: 'from step>onError.description'
```
Just keep it as a list, and .append any errors to it - no need to move it to the top of the list.

allowing pipeline operator to specify custom errors (optional) like:
```
- name: my.step
  onError:
     code: 'my err 111'
     description: 'blah blah blah {blah}'
```
