### ISSUE TITLE
The nested group call is unsupported when the parent section is in a loop.

### ISSUE THREAD

**Issue by Reskov** [pypyr/pypyr-cli#176]
I am using a lot of call groups in my project, they helped me to structure better my pipeline. Meanwhile, I face a little problem with calling subgroups.
I had prepared a little bit tricky example of pypyr usage to show the problem.
```yaml

steps:
  - name: pypyr.steps.default
    in:
      defaults:
        index: 0
  - name: pypyr.steps.call
    in:
      call:
        groups:
            - main
    while:
        stop: !py 'index > 2'

main:
  - name: pypyr.steps.contextmerge
    in:
      contextMerge:
        index: !py 'index + 1'

  - name: pypyr.steps.call
    in:
      call:
        groups:
          - subgroup

subgroup:
  - pypyr.steps.debug
```

This pipeline will stack in the infinity loop, due to the call section is overridden after the first iteration.

It seems that the nested group call is unsupported when the parent section is in a loop.
The problem is that the nested group is resetting 'call' key in the context, 
and unfortunately while from the main will call subgroup section instead of the main
How can we deal with this?
