### ISSUE TITLE
Context merge step does not support scalar keys

### ISSUE THREAD

**Issue by Reskov** [pypyr/pypyr-cli#179]
Seems that `pypyr.steps.contextmerge` do not work with the non-string keys. Following pipeline

```yaml

steps:
  - name: pypyr.steps.contextmerge
    in:
      contextMerge:
        1: 1
```
Gives me

```
TypeError: can only format on strings. 1 is a <class 'int'> instead.
```

Are numeric/scalar keys supported by the context merge step?
