### ISSUE TITLE
Better support for nested structure in setcontext steps

### ISSUE THREAD

**Issue by bleuse** [pypyr/pypyr-cli#47]
I have a use case where I want to add a new key-value pair to a dict in context. This pair is derived from other keys in the context. However, the entire value is replaced.

An example pipeline that exhibit this behavior is:
```nested.yaml
%YAML 1.2
---

steps:
    - name: pypyr.steps.assert
      description: Dummy step to supply the pipeline some arguments
      in:
          platform:
          keys:
              key1: value1
              key2: value2
          assertThis: True

    - name: pypyr.steps.echo
      in:
          echoMe: '{keys}'

    - name: pypyr.steps.contextsetf
      description: Add a new pair to keys
      in:
          contextSetf:
              keys:
                  merge_key: '{keys[key1]}_{keys[key2]}'

    - name: pypyr.steps.echo
      in:
          echoMe: '{keys}'

...
```

When I run this pipeline, it's output is:
```
2018-02-28 13:33:40 INFO:pypyr.steps.assert:run_step: assert evaluated to True
2018-02-28 13:33:40 INFO:pypyr.steps.echo:run_step: {'key1': 'value1', 'key2': 'value2'}
2018-02-28 13:33:40 INFO:pypyr.steps.contextsetf:run_step: Set 1 context items.
2018-02-28 13:33:40 INFO:pypyr.steps.echo:run_step: {'merge_key': 'value1_value2'}
```

I however expected the new dict keys to be added to the existing dict, and not a new dict to be created. The ouput I expected would be (note the difference on the 4th line:
```
2018-02-28 13:33:40 INFO:pypyr.steps.assert:run_step: assert evaluated to True
2018-02-28 13:33:40 INFO:pypyr.steps.echo:run_step: {'key1': 'value1', 'key2': 'value2'}
2018-02-28 13:33:40 INFO:pypyr.steps.contextsetf:run_step: Set 1 context items.
2018-02-28 13:33:40 INFO:pypyr.steps.echo:run_step: {'key1': 'value1', 'value2': 'key2', 'merge_key': 'value1_value2'}
```

**Comment by 345thomas** [comment]
Hi bleuse,

Thanks for you interest in pypyr! Yes, you're right, nested structures in setcontext and setcontextf end up replacing the entire value of that key. 

Here's how I generally do it:
1) assemble/concatenate your values at the point where you need them (on-the-fly, as it were), rather than prefilling the assembled value in a nested structure. 
An example of this approach in action: https://github.com/pypyr/pypyr-example/blob/master/pipelines/aws-s3.yaml
You'll notice that the nested `awsClientIn` structure is quite complex, but it uses `{bucket}` to substitute the requisite values at the right places in the nested structure. The degree to which this will work depends on the step you're using (the pypyraws package specifically goes to extra lengths with nested substitutions)
or
2) pre-fill an intermediate variable to hold the result of your concatenation/derivation, in case you're planning to re-use it multiple times. 

Here's a pipeline demonstrating the approaches of 1 and 2:
```yaml
steps:
  - name: pypyr.steps.echo
    description: Output echoMe
    in:
      key1: value1
      key2: value2
      nested_structure:
        nestedkey1: nestedvalue1
        nestedkey2: nestedvalue2
      echoMe: 'the original nested structure: {nested_structure}'
  - name: pypyr.steps.echo
    description: Output echoMe, constructing the output value on the fly
    in:
      echoMe: 'This was constructed on the fly at the time of use: {nested_structure[nestedkey1]}_{key2}'
  - name: pypyr.steps.contextsetf
    description: alternatively, create an intermediate holding variable for concatenated value
    in:
      contextSetf:
        mergedkey: '{nested_structure[nestedkey1]}_{key2}'
  - name: pypyr.steps.echo
    description: Output echoMe, from a prepared merged key that was set on the top level of context
    in:
        echoMe: 'This is from an intermediate pre-prepared top level context variable: {mergedkey}'
  - name: pypyr.steps.echo
    in:
        echoMe: 'and finally the nested structure has not been overwritten as result: {nested_structure}'
```
or 
3)  Use py step to manipulate context directly
```yaml
steps:
    - name: pypyr.steps.assert
      description: Dummy step to supply the pipeline some arguments
      in:
          platform:
          keys:
              key1: value1
              key2: value2
          assertThis: True

    - name: pypyr.steps.echo
      in:
          echoMe: '{keys}'

    - name: pypyr.steps.py
      description: set nested dict
      in:
          pycode: context['keys']['new_merged_key_set_from_py'] = context['keys']['key1'] + '_' + context['keys']['key2']

    - name: pypyr.steps.echo
      in:
          echoMe: '{keys}'
```

Hope this helps to address your immediate problem! But you have given me food for thought and I'm taking this on-board - I'll be thinking of ways of making dealing with nested sets more intuitive than it currently is, so thank you very much for your feedback! I'll keep this open for tracking this work item.
